{
    "code":0,
    "msg":"success",
    "data":{
        "current_page":"1",
        "total_page":13,
        "total_count":126,
        "list":[
            {
                "percent":42,
                "rank":1,
                "id":"14577",
                "fileName":"海陆的变迁 (1).pptx",
                "resourceName":"海陆的变迁 (1)",
                "stageId":"1",
                "subjectId":"15",
                "resourceType":null,
                "addWay":"0",
                "audience":"0",
                "checkStatus":"0",
                "createdBy":"6257194",
                "intro":null,
                "md5":"rw_xUMuIJEqxa.pptx",
                "phase":null,
                "publishStatus":"0",
                "shareLevel":"2",
                "src":"0",
                "submitTime":"2015-08-17 14:03:36",
                "updateTime":"2015-08-18 09:21:44",
                "updatedBy":"6257194",
                "seriesId":null,
                "deleted":"0",
                "fileSize":"17778274",
                "resourceFormat":"PPTX",
                "picker":"0",
                "pickStatus":"0",
                "pickTime":"0000-00-00 00:00:00",
                "chapterId":"1789",
                "topLevel":"0",
                "orgId":"1",
                "areaCode":null,
                "cityCode":null,
                "provinceCode":"P-RC000017",
                "schoolShareLevel":"0",
                "schoolCheckStatus":"0",
                "orgType":"4",
                "schoolCheckTime":"0000-00-00 00:00:00",
                "schoolCheckBy":"0",
                "checkTime":"2015-08-18 09:21:44",
                "checkBy":"12828",
                "areaCheckStatus":"0",
                "areaCheckTime":"0000-00-00 00:00:00",
                "areaCheckBy":"0",
                "cityCheckStatus":"0",
                "cityCheckTime":"0000-00-00 00:00:00",
                "cityCheckBy":"0",
                "provinceCheckStatus":"0",
                "provinceCheckTime":"0000-00-00 00:00:00",
                "provinceCheckBy":"0",
                "editBy":"0",
                "editTime":"0000-00-00 00:00:00",
                "areaCheckByName":null,
                "chapterName":"海陆的变迁",
                "cityCheckByName":null,
                "provinceCheckByName":null,
                "areaName":null,
                "cityName":null,
                "provinceName":null,
                "fav":"0",
                "ref":"1",
                "dnd":"2",
                "like":"0",
                "editByName":null,
                "orgName":"Okay学校",
                "schoolCheckByName":null,
                "stageName":"初中",
                "subjectName":"地理",
                "userName":"初中地理",
                "code":null,
                "copy":null,
                "favTime":null,
                "fid":null,
                "field":null,
                "operator":null,
                "series":null,
                "topicIds":null,
                "value":null,
                "operatorId":null,
                "pickerName":null,
                "refuseReason":null,
                "schoolRefuseReason":null,
                "updateByName":null,
                "userType":null,
                "shareTime":null,
                "checkByName":"刘蒙",
                "stage":{
                    "name":"初中",
                    "id":1
                },
                "subject":{
                    "name":"地理",
                    "id":15
                },
                "score":"9",
                "chapter1":"1787",
                "chapter2":"1789",
                "chapter3":"0",
                "highQual":"0",
                "moduleId":"0",
                "unitId":"0",
                "topicId":"0",
                "versionId":"124",
                "directoryId":"815",
                "timestamp":"1439791416",
                "ch1Name":"第二章 陆地和海洋",
                "ch2Name":"第二节 海陆的变迁",
                "ch3Name":null,
                "moduleName":null,
                "unitName":null,
                "topicName":null,
                "versionName":"人教版",
                "gradeName":"七年级上",
                "coverUrl":"http:\/\/rw.okjiaoyu.cn\/rw_xUMuIJEqxa.pptx_1.png?imageView2\/2\/w\/70"
            },
            {
                "percent":42,
                "rank":2,
                "id":"14563",
                "fileName":"地球的运动 (1).pptx",
                "resourceName":"地球的运动 (1)",
                "stageId":"1",
                "subjectId":"15",
                "resourceType":null,
                "addWay":"0",
                "audience":"0",
                "checkStatus":"0",
                "createdBy":"6257194",
                "intro":null,
                "md5":"rw_xULHlulmIE.pptx",
                "phase":null,
                "publishStatus":"0",
                "shareLevel":"2",
                "src":"0",
                "submitTime":"2015-08-17 13:50:45",
                "updateTime":"2015-08-18 09:22:57",
                "updatedBy":"6257194",
                "seriesId":null,
                "deleted":"0",
                "fileSize":"3762310",
                "resourceFormat":"PPTX",
                "picker":"0",
                "pickStatus":"0",
                "pickTime":"0000-00-00 00:00:00",
                "chapterId":"1784",
                "topLevel":"0",
                "orgId":"1",
                "areaCode":null,
                "cityCode":null,
                "provinceCode":"P-RC000017",
                "schoolShareLevel":"0",
                "schoolCheckStatus":"0",
                "orgType":"4",
                "schoolCheckTime":"0000-00-00 00:00:00",
                "schoolCheckBy":"0",
                "checkTime":"2015-08-18 09:22:57",
                "checkBy":"12828",
                "areaCheckStatus":"0",
                "areaCheckTime":"0000-00-00 00:00:00",
                "areaCheckBy":"0",
                "cityCheckStatus":"0",
                "cityCheckTime":"0000-00-00 00:00:00",
                "cityCheckBy":"0",
                "provinceCheckStatus":"0",
                "provinceCheckTime":"0000-00-00 00:00:00",
                "provinceCheckBy":"0",
                "editBy":"0",
                "editTime":"0000-00-00 00:00:00",
                "areaCheckByName":null,
                "chapterName":"地球的运动",
                "cityCheckByName":null,
                "provinceCheckByName":null,
                "areaName":null,
                "cityName":null,
                "provinceName":null,
                "fav":"0",
                "ref":"1",
                "dnd":"0",
                "like":"0",
                "editByName":null,
                "orgName":"Okay学校",
                "schoolCheckByName":null,
                "stageName":"初中",
                "subjectName":"地理",
                "userName":"初中地理",
                "code":null,
                "copy":null,
                "favTime":null,
                "fid":null,
                "field":null,
                "operator":null,
                "series":null,
                "topicIds":null,
                "value":null,
                "operatorId":null,
                "pickerName":null,
                "refuseReason":null,
                "schoolRefuseReason":null,
                "updateByName":null,
                "userType":null,
                "shareTime":null,
                "checkByName":"刘蒙",
                "stage":{
                    "name":"初中",
                    "id":1
                },
                "subject":{
                    "name":"地理",
                    "id":15
                },
                "score":"5",
                "chapter1":"1782",
                "chapter2":"1784",
                "chapter3":"0",
                "highQual":"0",
                "moduleId":"0",
                "unitId":"0",
                "topicId":"0",
                "versionId":"124",
                "directoryId":"815",
                "timestamp":"1439790645",
                "ch1Name":"第一章 地球和地图",
                "ch2Name":"第二节 地球的运动",
                "ch3Name":null,
                "moduleName":null,
                "unitName":null,
                "topicName":null,
                "versionName":"人教版",
                "gradeName":"七年级上",
                "coverUrl":"http:\/\/rw.okjiaoyu.cn\/rw_xULHlulmIE.pptx_1.png?imageView2\/2\/w\/70"
            },
            {
                "percent":42,
                "rank":3,
                "id":"14573",
                "fileName":"大洲和大洋 (2).pptx",
                "resourceName":"大洲和大洋 (2)",
                "stageId":"1",
                "subjectId":"15",
                "resourceType":null,
                "addWay":"0",
                "audience":"0",
                "checkStatus":"0",
                "createdBy":"6257194",
                "intro":null,
                "md5":"rw_xUMglgpf0I.pptx",
                "phase":null,
                "publishStatus":"0",
                "shareLevel":"2",
                "src":"0",
                "submitTime":"2015-08-17 14:00:04",
                "updateTime":"2015-08-18 09:22:13",
                "updatedBy":"6257194",
                "seriesId":null,
                "deleted":"0",
                "fileSize":"18821182",
                "resourceFormat":"PPTX",
                "picker":"0",
                "pickStatus":"0",
                "pickTime":"0000-00-00 00:00:00",
                "chapterId":"1788",
                "topLevel":"0",
                "orgId":"1",
                "areaCode":null,
                "cityCode":null,
                "provinceCode":"P-RC000017",
                "schoolShareLevel":"0",
                "schoolCheckStatus":"0",
                "orgType":"4",
                "schoolCheckTime":"0000-00-00 00:00:00",
                "schoolCheckBy":"0",
                "checkTime":"2015-08-18 09:22:13",
                "checkBy":"12828",
                "areaCheckStatus":"0",
                "areaCheckTime":"0000-00-00 00:00:00",
                "areaCheckBy":"0",
                "cityCheckStatus":"0",
                "cityCheckTime":"0000-00-00 00:00:00",
                "cityCheckBy":"0",
                "provinceCheckStatus":"0",
                "provinceCheckTime":"0000-00-00 00:00:00",
                "provinceCheckBy":"0",
                "editBy":"0",
                "editTime":"0000-00-00 00:00:00",
                "areaCheckByName":null,
                "chapterName":"大洲和大洋",
                "cityCheckByName":null,
                "provinceCheckByName":null,
                "areaName":null,
                "cityName":null,
                "provinceName":null,
                "fav":"0",
                "ref":"1",
                "dnd":"0",
                "like":"0",
                "editByName":null,
                "orgName":"Okay学校",
                "schoolCheckByName":null,
                "stageName":"初中",
                "subjectName":"地理",
                "userName":"初中地理",
                "code":null,
                "copy":null,
                "favTime":null,
                "fid":null,
                "field":null,
                "operator":null,
                "series":null,
                "topicIds":null,
                "value":null,
                "operatorId":null,
                "pickerName":null,
                "refuseReason":null,
                "schoolRefuseReason":null,
                "updateByName":null,
                "userType":null,
                "shareTime":null,
                "checkByName":"刘蒙",
                "stage":{
                    "name":"初中",
                    "id":1
                },
                "subject":{
                    "name":"地理",
                    "id":15
                },
                "score":"5",
                "chapter1":"1787",
                "chapter2":"1788",
                "chapter3":"0",
                "highQual":"0",
                "moduleId":"0",
                "unitId":"0",
                "topicId":"0",
                "versionId":"124",
                "directoryId":"815",
                "timestamp":"1439791204",
                "ch1Name":"第二章 陆地和海洋",
                "ch2Name":"第一节 大洲和大洋",
                "ch3Name":null,
                "moduleName":null,
                "unitName":null,
                "topicName":null,
                "versionName":"人教版",
                "gradeName":"七年级上",
                "coverUrl":"http:\/\/rw.okjiaoyu.cn\/rw_courseware_icon.png"
            },
            {
                "percent":42,
                "rank":4,
                "id":"14576",
                "fileName":"海陆的变迁 (2).pptx",
                "resourceName":"海陆的变迁 (2)",
                "stageId":"1",
                "subjectId":"15",
                "resourceType":null,
                "addWay":"0",
                "audience":"0",
                "checkStatus":"0",
                "createdBy":"6257194",
                "intro":null,
                "md5":"rw_xUMvMb2HNm.pptx",
                "phase":null,
                "publishStatus":"0",
                "shareLevel":"2",
                "src":"0",
                "submitTime":"2015-08-17 14:02:52",
                "updateTime":"2015-08-18 09:21:56",
                "updatedBy":"6257194",
                "seriesId":null,
                "deleted":"0",
                "fileSize":"13336360",
                "resourceFormat":"PPTX",
                "picker":"0",
                "pickStatus":"0",
                "pickTime":"0000-00-00 00:00:00",
                "chapterId":"1789",
                "topLevel":"0",
                "orgId":"1",
                "areaCode":null,
                "cityCode":null,
                "provinceCode":"P-RC000017",
                "schoolShareLevel":"0",
                "schoolCheckStatus":"0",
                "orgType":"4",
                "schoolCheckTime":"0000-00-00 00:00:00",
                "schoolCheckBy":"0",
                "checkTime":"2015-08-18 09:21:56",
                "checkBy":"12828",
                "areaCheckStatus":"0",
                "areaCheckTime":"0000-00-00 00:00:00",
                "areaCheckBy":"0",
                "cityCheckStatus":"0",
                "cityCheckTime":"0000-00-00 00:00:00",
                "cityCheckBy":"0",
                "provinceCheckStatus":"0",
                "provinceCheckTime":"0000-00-00 00:00:00",
                "provinceCheckBy":"0",
                "editBy":"0",
                "editTime":"0000-00-00 00:00:00",
                "areaCheckByName":null,
                "chapterName":"海陆的变迁",
                "cityCheckByName":null,
                "provinceCheckByName":null,
                "areaName":null,
                "cityName":null,
                "provinceName":null,
                "fav":"0",
                "ref":"1",
                "dnd":"0",
                "like":"0",
                "editByName":null,
                "orgName":"Okay学校",
                "schoolCheckByName":null,
                "stageName":"初中",
                "subjectName":"地理",
                "userName":"初中地理",
                "code":null,
                "copy":null,
                "favTime":null,
                "fid":null,
                "field":null,
                "operator":null,
                "series":null,
                "topicIds":null,
                "value":null,
                "operatorId":null,
                "pickerName":null,
                "refuseReason":null,
                "schoolRefuseReason":null,
                "updateByName":null,
                "userType":null,
                "shareTime":null,
                "checkByName":"刘蒙",
                "stage":{
                    "name":"初中",
                    "id":1
                },
                "subject":{
                    "name":"地理",
                    "id":15
                },
                "score":"5",
                "chapter1":"1787",
                "chapter2":"1789",
                "chapter3":"0",
                "highQual":"0",
                "moduleId":"0",
                "unitId":"0",
                "topicId":"0",
                "versionId":"124",
                "directoryId":"815",
                "timestamp":"1439791372",
                "ch1Name":"第二章 陆地和海洋",
                "ch2Name":"第二节 海陆的变迁",
                "ch3Name":null,
                "moduleName":null,
                "unitName":null,
                "topicName":null,
                "versionName":"人教版",
                "gradeName":"七年级上",
                "coverUrl":"http:\/\/rw.okjiaoyu.cn\/rw_courseware_icon.png"
            },
            {
                "percent":42,
                "rank":5,
                "id":"14580",
                "fileName":"多变的天气 (1).pptx",
                "resourceName":"多变的天气 (1)",
                "stageId":"1",
                "subjectId":"15",
                "resourceType":null,
                "addWay":"0",
                "audience":"0",
                "checkStatus":"0",
                "createdBy":"6257194",
                "intro":null,
                "md5":"rw_xUMFxZRsGs.pptx",
                "phase":null,
                "publishStatus":"0",
                "shareLevel":"2",
                "src":"0",
                "submitTime":"2015-08-17 14:04:31",
                "updateTime":"2015-08-18 09:21:26",
                "updatedBy":"6257194",
                "seriesId":null,
                "deleted":"0",
                "fileSize":"7106058",
                "resourceFormat":"PPTX",
                "picker":"0",
                "pickStatus":"0",
                "pickTime":"0000-00-00 00:00:00",
                "chapterId":"1791",
                "topLevel":"0",
                "orgId":"1",
                "areaCode":null,
                "cityCode":null,
                "provinceCode":"P-RC000017",
                "schoolShareLevel":"0",
                "schoolCheckStatus":"0",
                "orgType":"4",
                "schoolCheckTime":"0000-00-00 00:00:00",
                "schoolCheckBy":"0",
                "checkTime":"2015-08-18 09:21:26",
                "checkBy":"12828",
                "areaCheckStatus":"0",
                "areaCheckTime":"0000-00-00 00:00:00",
                "areaCheckBy":"0",
                "cityCheckStatus":"0",
                "cityCheckTime":"0000-00-00 00:00:00",
                "cityCheckBy":"0",
                "provinceCheckStatus":"0",
                "provinceCheckTime":"0000-00-00 00:00:00",
                "provinceCheckBy":"0",
                "editBy":"0",
                "editTime":"0000-00-00 00:00:00",
                "areaCheckByName":null,
                "chapterName":"多变的天气",
                "cityCheckByName":null,
                "provinceCheckByName":null,
                "areaName":null,
                "cityName":null,
                "provinceName":null,
                "fav":"0",
                "ref":"1",
                "dnd":"0",
                "like":"0",
                "editByName":null,
                "orgName":"Okay学校",
                "schoolCheckByName":null,
                "stageName":"初中",
                "subjectName":"地理",
                "userName":"初中地理",
                "code":null,
                "copy":null,
                "favTime":null,
                "fid":null,
                "field":null,
                "operator":null,
                "series":null,
                "topicIds":null,
                "value":null,
                "operatorId":null,
                "pickerName":null,
                "refuseReason":null,
                "schoolRefuseReason":null,
                "updateByName":null,
                "userType":null,
                "shareTime":null,
                "checkByName":"刘蒙",
                "stage":{
                    "name":"初中",
                    "id":1
                },
                "subject":{
                    "name":"地理",
                    "id":15
                },
                "score":"5",
                "chapter1":"1790",
                "chapter2":"1791",
                "chapter3":"0",
                "highQual":"0",
                "moduleId":"0",
                "unitId":"0",
                "topicId":"0",
                "versionId":"124",
                "directoryId":"815",
                "timestamp":"1439791471",
                "ch1Name":"第三章 天气和气候",
                "ch2Name":"第一节 多变的天气",
                "ch3Name":null,
                "moduleName":null,
                "unitName":null,
                "topicName":null,
                "versionName":"人教版",
                "gradeName":"七年级上",
                "coverUrl":"http:\/\/rw.okjiaoyu.cn\/rw_xUMFxZRsGs.pptx_1.png?imageView2\/2\/w\/70"
            },
            {
                "percent":40,
                "rank":6,
                "id":"14589",
                "fileName":"降水和降水的分布 (1).pptx",
                "resourceName":"降水和降水的分布 (1)",
                "stageId":"1",
                "subjectId":"15",
                "resourceType":null,
                "addWay":"0",
                "audience":"0",
                "checkStatus":"0",
                "createdBy":"6257194",
                "intro":null,
                "md5":"rw_xUNEGvNgFG.pptx",
                "phase":null,
                "publishStatus":"0",
                "shareLevel":"2",
                "src":"0",
                "submitTime":"2015-08-17 14:17:18",
                "updateTime":"2015-08-18 09:18:26",
                "updatedBy":"6257194",
                "seriesId":null,
                "deleted":"0",
                "fileSize":"1617408",
                "resourceFormat":"PPTX",
                "picker":"0",
                "pickStatus":"0",
                "pickTime":"0000-00-00 00:00:00",
                "chapterId":"1793",
                "topLevel":"0",
                "orgId":"1",
                "areaCode":null,
                "cityCode":null,
                "provinceCode":"P-RC000017",
                "schoolShareLevel":"0",
                "schoolCheckStatus":"0",
                "orgType":"4",
                "schoolCheckTime":"0000-00-00 00:00:00",
                "schoolCheckBy":"0",
                "checkTime":"2015-08-18 09:18:26",
                "checkBy":"12828",
                "areaCheckStatus":"0",
                "areaCheckTime":"0000-00-00 00:00:00",
                "areaCheckBy":"0",
                "cityCheckStatus":"0",
                "cityCheckTime":"0000-00-00 00:00:00",
                "cityCheckBy":"0",
                "provinceCheckStatus":"0",
                "provinceCheckTime":"0000-00-00 00:00:00",
                "provinceCheckBy":"0",
                "editBy":"0",
                "editTime":"0000-00-00 00:00:00",
                "areaCheckByName":null,
                "chapterName":"降水的变化与分布",
                "cityCheckByName":null,
                "provinceCheckByName":null,
                "areaName":null,
                "cityName":null,
                "provinceName":null,
                "fav":"0",
                "ref":"1",
                "dnd":"0",
                "like":"0",
                "editByName":null,
                "orgName":"Okay学校",
                "schoolCheckByName":null,
                "stageName":"初中",
                "subjectName":"地理",
                "userName":"初中地理",
                "code":null,
                "copy":null,
                "favTime":null,
                "fid":null,
                "field":null,
                "operator":null,
                "series":null,
                "topicIds":null,
                "value":null,
                "operatorId":null,
                "pickerName":null,
                "refuseReason":null,
                "schoolRefuseReason":null,
                "updateByName":null,
                "userType":null,
                "shareTime":null,
                "checkByName":"刘蒙",
                "stage":{
                    "name":"初中",
                    "id":1
                },
                "subject":{
                    "name":"地理",
                    "id":15
                },
                "score":"5",
                "chapter1":"1790",
                "chapter2":"1793",
                "chapter3":"0",
                "highQual":"0",
                "moduleId":"0",
                "unitId":"0",
                "topicId":"0",
                "versionId":"124",
                "directoryId":"815",
                "timestamp":"1439792238",
                "ch1Name":"第三章 天气和气候",
                "ch2Name":"第三节 降水的变化与分布",
                "ch3Name":null,
                "moduleName":null,
                "unitName":null,
                "topicName":null,
                "versionName":"人教版",
                "gradeName":"七年级上",
                "coverUrl":"http:\/\/rw.okjiaoyu.cn\/rw_courseware_icon.png"
            },
            {
                "percent":39,
                "rank":7,
                "id":"14562",
                "fileName":"地球和地球仪课件 (4).pptx",
                "resourceName":"地球和地球仪课件 (4)",
                "stageId":"1",
                "subjectId":"15",
                "resourceType":null,
                "addWay":"0",
                "audience":"0",
                "checkStatus":"0",
                "createdBy":"6257194",
                "intro":null,
                "md5":"rw_xULBRw0jLO.pptx",
                "phase":null,
                "publishStatus":"0",
                "shareLevel":"2",
                "src":"0",
                "submitTime":"2015-08-17 13:49:35",
                "updateTime":"2015-08-18 09:23:00",
                "updatedBy":"6257194",
                "seriesId":null,
                "deleted":"0",
                "fileSize":"11728298",
                "resourceFormat":"PPTX",
                "picker":"0",
                "pickStatus":"0",
                "pickTime":"0000-00-00 00:00:00",
                "chapterId":"1783",
                "topLevel":"0",
                "orgId":"1",
                "areaCode":null,
                "cityCode":null,
                "provinceCode":"P-RC000017",
                "schoolShareLevel":"0",
                "schoolCheckStatus":"0",
                "orgType":"4",
                "schoolCheckTime":"0000-00-00 00:00:00",
                "schoolCheckBy":"0",
                "checkTime":"2015-08-18 09:23:00",
                "checkBy":"12828",
                "areaCheckStatus":"0",
                "areaCheckTime":"0000-00-00 00:00:00",
                "areaCheckBy":"0",
                "cityCheckStatus":"0",
                "cityCheckTime":"0000-00-00 00:00:00",
                "cityCheckBy":"0",
                "provinceCheckStatus":"0",
                "provinceCheckTime":"0000-00-00 00:00:00",
                "provinceCheckBy":"0",
                "editBy":"0",
                "editTime":"0000-00-00 00:00:00",
                "areaCheckByName":null,
                "chapterName":"地球和地球仪",
                "cityCheckByName":null,
                "provinceCheckByName":null,
                "areaName":null,
                "cityName":null,
                "provinceName":null,
                "fav":"0",
                "ref":"1",
                "dnd":"0",
                "like":"0",
                "editByName":null,
                "orgName":"Okay学校",
                "schoolCheckByName":null,
                "stageName":"初中",
                "subjectName":"地理",
                "userName":"初中地理",
                "code":null,
                "copy":null,
                "favTime":null,
                "fid":null,
                "field":null,
                "operator":null,
                "series":null,
                "topicIds":null,
                "value":null,
                "operatorId":null,
                "pickerName":null,
                "refuseReason":null,
                "schoolRefuseReason":null,
                "updateByName":null,
                "userType":null,
                "shareTime":null,
                "checkByName":"刘蒙",
                "stage":{
                    "name":"初中",
                    "id":1
                },
                "subject":{
                    "name":"地理",
                    "id":15
                },
                "score":"5",
                "chapter1":"1782",
                "chapter2":"1783",
                "chapter3":"0",
                "highQual":"0",
                "moduleId":"0",
                "unitId":"0",
                "topicId":"0",
                "versionId":"124",
                "directoryId":"815",
                "timestamp":"1439790575",
                "ch1Name":"第一章 地球和地图",
                "ch2Name":"第一节 地球和地球仪",
                "ch3Name":null,
                "moduleName":null,
                "unitName":null,
                "topicName":null,
                "versionName":"人教版",
                "gradeName":"七年级上",
                "coverUrl":"http:\/\/rw.okjiaoyu.cn\/rw_xULBRw0jLO.pptx_1.png?imageView2\/2\/w\/70"
            },
            {
                "percent":39,
                "rank":8,
                "id":"14559",
                "fileName":"地球和地球仪课件 (1).pptx",
                "resourceName":"地球和地球仪课件 (1)",
                "stageId":"1",
                "subjectId":"15",
                "resourceType":null,
                "addWay":"0",
                "audience":"0",
                "checkStatus":"0",
                "createdBy":"6257194",
                "intro":null,
                "md5":"rw_xULw1o6koM.pptx",
                "phase":null,
                "publishStatus":"0",
                "shareLevel":"2",
                "src":"0",
                "submitTime":"2015-08-17 13:48:47",
                "updateTime":"2015-08-18 09:23:17",
                "updatedBy":"6257194",
                "seriesId":null,
                "deleted":"0",
                "fileSize":"16089514",
                "resourceFormat":"PPTX",
                "picker":"0",
                "pickStatus":"0",
                "pickTime":"0000-00-00 00:00:00",
                "chapterId":"1783",
                "topLevel":"0",
                "orgId":"1",
                "areaCode":null,
                "cityCode":null,
                "provinceCode":"P-RC000017",
                "schoolShareLevel":"0",
                "schoolCheckStatus":"0",
                "orgType":"4",
                "schoolCheckTime":"0000-00-00 00:00:00",
                "schoolCheckBy":"0",
                "checkTime":"2015-08-18 09:23:17",
                "checkBy":"12828",
                "areaCheckStatus":"0",
                "areaCheckTime":"0000-00-00 00:00:00",
                "areaCheckBy":"0",
                "cityCheckStatus":"0",
                "cityCheckTime":"0000-00-00 00:00:00",
                "cityCheckBy":"0",
                "provinceCheckStatus":"0",
                "provinceCheckTime":"0000-00-00 00:00:00",
                "provinceCheckBy":"0",
                "editBy":"0",
                "editTime":"0000-00-00 00:00:00",
                "areaCheckByName":null,
                "chapterName":"地球和地球仪",
                "cityCheckByName":null,
                "provinceCheckByName":null,
                "areaName":null,
                "cityName":null,
                "provinceName":null,
                "fav":"0",
                "ref":"0",
                "dnd":"1",
                "like":"0",
                "editByName":null,
                "orgName":"Okay学校",
                "schoolCheckByName":null,
                "stageName":"初中",
                "subjectName":"地理",
                "userName":"初中地理",
                "code":null,
                "copy":null,
                "favTime":null,
                "fid":null,
                "field":null,
                "operator":null,
                "series":null,
                "topicIds":null,
                "value":null,
                "operatorId":null,
                "pickerName":null,
                "refuseReason":null,
                "schoolRefuseReason":null,
                "updateByName":null,
                "userType":null,
                "shareTime":null,
                "checkByName":"刘蒙",
                "stage":{
                    "name":"初中",
                    "id":1
                },
                "subject":{
                    "name":"地理",
                    "id":15
                },
                "score":"2",
                "chapter1":"1782",
                "chapter2":"1783",
                "chapter3":"0",
                "highQual":"0",
                "moduleId":"0",
                "unitId":"0",
                "topicId":"0",
                "versionId":"124",
                "directoryId":"815",
                "timestamp":"1439790527",
                "ch1Name":"第一章 地球和地图",
                "ch2Name":"第一节 地球和地球仪",
                "ch3Name":null,
                "moduleName":null,
                "unitName":null,
                "topicName":null,
                "versionName":"人教版",
                "gradeName":"七年级上",
                "coverUrl":"http:\/\/rw.okjiaoyu.cn\/rw_xULw1o6koM.pptx_1.png?imageView2\/2\/w\/70"
            },
            {
                "percent":42,
                "rank":9,
                "id":"14564",
                "fileName":"地球的运动 (3).pptx",
                "resourceName":"地球的运动 (3)",
                "stageId":"1",
                "subjectId":"15",
                "resourceType":null,
                "addWay":"0",
                "audience":"0",
                "checkStatus":"0",
                "createdBy":"6257194",
                "intro":null,
                "md5":"rw_xULKRHU0vK.pptx",
                "phase":null,
                "publishStatus":"0",
                "shareLevel":"2",
                "src":"0",
                "submitTime":"2015-08-17 13:51:45",
                "updateTime":"2015-08-18 09:22:45",
                "updatedBy":"6257194",
                "seriesId":null,
                "deleted":"0",
                "fileSize":"6477312",
                "resourceFormat":"PPTX",
                "picker":"0",
                "pickStatus":"0",
                "pickTime":"0000-00-00 00:00:00",
                "chapterId":"1784",
                "topLevel":"0",
                "orgId":"1",
                "areaCode":null,
                "cityCode":null,
                "provinceCode":"P-RC000017",
                "schoolShareLevel":"0",
                "schoolCheckStatus":"0",
                "orgType":"4",
                "schoolCheckTime":"0000-00-00 00:00:00",
                "schoolCheckBy":"0",
                "checkTime":"2015-08-18 09:22:45",
                "checkBy":"12828",
                "areaCheckStatus":"0",
                "areaCheckTime":"0000-00-00 00:00:00",
                "areaCheckBy":"0",
                "cityCheckStatus":"0",
                "cityCheckTime":"0000-00-00 00:00:00",
                "cityCheckBy":"0",
                "provinceCheckStatus":"0",
                "provinceCheckTime":"0000-00-00 00:00:00",
                "provinceCheckBy":"0",
                "editBy":"0",
                "editTime":"0000-00-00 00:00:00",
                "areaCheckByName":null,
                "chapterName":"地球的运动",
                "cityCheckByName":null,
                "provinceCheckByName":null,
                "areaName":null,
                "cityName":null,
                "provinceName":null,
                "fav":"0",
                "ref":"0",
                "dnd":"0",
                "like":"0",
                "editByName":null,
                "orgName":"Okay学校",
                "schoolCheckByName":null,
                "stageName":"初中",
                "subjectName":"地理",
                "userName":"初中地理",
                "code":null,
                "copy":null,
                "favTime":null,
                "fid":null,
                "field":null,
                "operator":null,
                "series":null,
                "topicIds":null,
                "value":null,
                "operatorId":null,
                "pickerName":null,
                "refuseReason":null,
                "schoolRefuseReason":null,
                "updateByName":null,
                "userType":null,
                "shareTime":null,
                "checkByName":"刘蒙",
                "stage":{
                    "name":"初中",
                    "id":1
                },
                "subject":{
                    "name":"地理",
                    "id":15
                },
                "score":"0",
                "chapter1":"1782",
                "chapter2":"1784",
                "chapter3":"0",
                "highQual":"0",
                "moduleId":"0",
                "unitId":"0",
                "topicId":"0",
                "versionId":"124",
                "directoryId":"815",
                "timestamp":"1439790705",
                "ch1Name":"第一章 地球和地图",
                "ch2Name":"第二节 地球的运动",
                "ch3Name":null,
                "moduleName":null,
                "unitName":null,
                "topicName":null,
                "versionName":"人教版",
                "gradeName":"七年级上",
                "coverUrl":"http:\/\/rw.okjiaoyu.cn\/rw_courseware_icon.png"
            },
            {
                "percent":42,
                "rank":10,
                "id":"14565",
                "fileName":"地球的运动 (2).pptx",
                "resourceName":"地球的运动 (2)",
                "stageId":"1",
                "subjectId":"15",
                "resourceType":null,
                "addWay":"0",
                "audience":"0",
                "checkStatus":"0",
                "createdBy":"6257194",
                "intro":null,
                "md5":"rw_xULIuOuc7K.pptx",
                "phase":null,
                "publishStatus":"0",
                "shareLevel":"2",
                "src":"0",
                "submitTime":"2015-08-17 13:52:13",
                "updateTime":"2015-08-18 09:22:40",
                "updatedBy":"6257194",
                "seriesId":null,
                "deleted":"0",
                "fileSize":"17977150",
                "resourceFormat":"PPTX",
                "picker":"0",
                "pickStatus":"0",
                "pickTime":"0000-00-00 00:00:00",
                "chapterId":"1784",
                "topLevel":"0",
                "orgId":"1",
                "areaCode":null,
                "cityCode":null,
                "provinceCode":"P-RC000017",
                "schoolShareLevel":"0",
                "schoolCheckStatus":"0",
                "orgType":"4",
                "schoolCheckTime":"0000-00-00 00:00:00",
                "schoolCheckBy":"0",
                "checkTime":"2015-08-18 09:22:40",
                "checkBy":"12828",
                "areaCheckStatus":"0",
                "areaCheckTime":"0000-00-00 00:00:00",
                "areaCheckBy":"0",
                "cityCheckStatus":"0",
                "cityCheckTime":"0000-00-00 00:00:00",
                "cityCheckBy":"0",
                "provinceCheckStatus":"0",
                "provinceCheckTime":"0000-00-00 00:00:00",
                "provinceCheckBy":"0",
                "editBy":"0",
                "editTime":"0000-00-00 00:00:00",
                "areaCheckByName":null,
                "chapterName":"地球的运动",
                "cityCheckByName":null,
                "provinceCheckByName":null,
                "areaName":null,
                "cityName":null,
                "provinceName":null,
                "fav":"0",
                "ref":"0",
                "dnd":"0",
                "like":"0",
                "editByName":null,
                "orgName":"Okay学校",
                "schoolCheckByName":null,
                "stageName":"初中",
                "subjectName":"地理",
                "userName":"初中地理",
                "code":null,
                "copy":null,
                "favTime":null,
                "fid":null,
                "field":null,
                "operator":null,
                "series":null,
                "topicIds":null,
                "value":null,
                "operatorId":null,
                "pickerName":null,
                "refuseReason":null,
                "schoolRefuseReason":null,
                "updateByName":null,
                "userType":null,
                "shareTime":null,
                "checkByName":"刘蒙",
                "stage":{
                    "name":"初中",
                    "id":1
                },
                "subject":{
                    "name":"地理",
                    "id":15
                },
                "score":"0",
                "chapter1":"1782",
                "chapter2":"1784",
                "chapter3":"0",
                "highQual":"0",
                "moduleId":"0",
                "unitId":"0",
                "topicId":"0",
                "versionId":"124",
                "directoryId":"815",
                "timestamp":"1439790733",
                "ch1Name":"第一章 地球和地图",
                "ch2Name":"第二节 地球的运动",
                "ch3Name":null,
                "moduleName":null,
                "unitName":null,
                "topicName":null,
                "versionName":"人教版",
                "gradeName":"七年级上",
                "coverUrl":"http:\/\/rw.okjiaoyu.cn\/rw_xULIuOuc7K.pptx_1.png?imageView2\/2\/w\/70"
            }
        ]
    }
}